config/routes.rb
Catala::Application.routes.draw do
  devise_for :users, controller: 'registrations'
  
  get 'products/search'
  get 'pag_notifications/create'
  get 'payments/new' => 'payments#new'
  get 'city/get_by_state/:state_id', to: 'city#get_by_state'
  get 'image_uploader' => 'image_uploader#upload' 

 
  resources :categories do 
    resources :ads do
      
      resources :products do
        member do 
          get 'search'
        end
      end

      resources :payments
    end
  end

  root 'welcome#index'
end

app/models/ad.rb
class Ad < ActiveRecord::Base
    belongs_to :category
    belongs_to :user

    has_many :payments
    has_many :products

    has_one :address
    accepts_nested_attributes_for :address, allow_destroy: true
    
    validates :name, presence: true, length: { minimum: 1 }
    validates :description, presence: true, length: { minimum: 10 }

    PRICE_PER_MONTH = 30

    extend FriendlyId
    friendly_id :name, use: :slugged

    private
	    def should_generate_new_friendly_id?
	    	new_record?
	    end    
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  before_filter :is_user?, only: [:update, :edit, :destroy, :new]

  include AdsHelper
  include ProductsHelper
  
  # GET /ads
  # GET /ads.json
  def index
    @ads ||= Ad.all.where(hidden: false)
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @category = Category.friendly.find( params[:category_id] )
    @ad = @category.ads.build
  end

  # GET /ads/1/edit
  def edit
      @category = Category.friendly.find( params[:category_id] )
  end

  # POST /ads
  # POST /ads.json
  def create
    @category = Category.friendly.find( params[:category_id] )
    # TODO: clear :expires_at field here
    @ad = @category.ads.build( ad_params )
    
    if current_user.admin? 
      @ad.hidden = false
    end

    if request.xhr?
      if @ad.save
        render text: @ad.slug
      else
        render text: 'error'
      end
    else
      respond_to do |format|
        if @ad.save
          format.html { redirect_to ad_url( @ad ), notice: 'Seu anúncio foi criado com sucesso' }
          format.json { render action: 'show', status: :created, location: @ad }
        else
          format.html { render action: 'new' }
          format.json { render json: @ad.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Anúncio atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to '/' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find_by slug: params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list throug
    def ad_params
        address = [:id, :street, :zipcode, :neighbourhood, :complement, :phone_area_code, :phone_number, :state_id, :city_id]
        params.require(:ad).permit(
          :expires_at, :name, :slogan, :logo_url,:site_url,
          :state, :city, :district, :cep, :tel, :description, 
          :category_id, :user_id, :products, address_attributes: address
        )
    end
    
    def is_user?
        redirect_to '/', notice: 'Você não está logado' unless authenticate_user!
    end
end

app/helpers/ads_helper.rb
module AdsHelper
    def ad_url(ad)
        "/categories/#{ad.category.slug}/ads/#{ad.slug}"
    end
    
    def ads_path(cat)
        "/categories/#{cat.slug}/ads/"    
    end
    
    def edit_path(ad)
        "/categories/#{ad.category.slug}/ads/#{ad.slug}/edit"
    end
    
    def is_admin_or_owner?(ad)
        if user_signed_in?
           current_user.admin? or ad.user.id == current_user.id
        end
    end

    def is_admin_or_waiting_user?
        if user_signed_in?
            current_user.admin? or current_user.paid_but_not_yet_posted?
        end
    end
end

app/views/ads/_ad_mini.html.erb
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <%= image_tag(ad.logo_url, width: 300, height: 200) %>
        <div class="caption">
            <h3 class='ads-title'><%= ad.name %></h3>
            <p class='musted ads-slogan'><%= ad.slogan %></p>
            <div class='ads-contact'>
                <% #TODO: Make a helper to this [horror here!] %>
                <%= "#{ad.address.street}, #{ad.address.city.name}, #{ad.address.city.state.name}" if ad.address %>
            </div>
            <p class='ads-description'><%= strip_tags(ad.description[0..60]) %>...</p>
            <p>
                <%= link_to "Ver mais", ad_url(ad), class: 'btn btn-primary', role: 'button' %> 
                <%= 
                    link_to( 
                        'Editar', 
                        edit_category_ad_path(ad.category, ad), 
                        class: 'btn btn-danger' 
                    ) if is_admin_or_owner?(ad)
                %>                
            </p>
        </div>
    </div>
</div>

app/views/ads/_ad_panel.html.erb
<h3>Seus anúncios</h3>
<ul class='list-style-none'>
<% user.ads.each do |ad| # showing ads %>
  <li>
    <div class='well'>
    <h3><%= link_to ad.name, ad_url(ad) %></h3>
   
    <% unless ad.payments.empty? # If user paid %>
      <p class='lead'>
        <%= 'Este anúncio está expirado' if ad.payments.last.status === -1 %>
      </p>
      <% if ad.payments.last.status.nil? %>
          <h4>Este pagamento não foi finalizado, tente pagar novamente</h4>
          <%= 
            link_to 'Clique aqui para realizar um pagamento', new_category_ad_payment_path(ad.category_id, ad), class: 'btn btn-success' 
          %>            
      <% elsif ad.payments.last.status.zero? %>
          <h4>Seu pagamento ainda está sendo processado, logo seu anúncio estará visível :)</h4> 
      <% else %>
        <h4>A data de expiração do pagamento é <%= ad.payments.last.expires_at %></h4>
      <% end %>     

    <% else  # If user doesn't paid %>
      <p class='lead'>
        <%= 'Você ainda não realizou um pagamento para este anúncio' %>
      </p>

      <%= link_to 'Clique aqui para realizar um pagamento', new_category_ad_payment_path(ad.category_id, ad), class: 'btn btn-success' %>

    <% end # else %>  

       <%= link_to( 
          'Apagar', 
          category_ad_path(ad.category, ad), 
          class: 'btn btn-danger', 
          data: { confirm: 'Tem certeza? (apagar é irreversível!)' }, 
          method: 'delete' 
      ) %>

       <%= link_to( 
          'Editar', 
          edit_category_ad_path(ad.category, ad), 
          class: 'btn btn-info'
      ) %>      
         
    </div>
  </li>
<% end # each %>
</ul>

app/views/ads/_form.html.erb
<%= cloudinary_js_config %>
<div>
<%= form_for([@category, @ad]) do |f| %>

  <% if @ad.errors.any? %>
    <div id="error_explanation" style='display: none'>
      <ul class='table table-striped'>
      <% @ad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <script type="text/javascript">
    $(function(){
      Modal
        .header('<%= @ad.errors.count %> erro(s) não permitiram você de salvar o anúncio:')
        .body($('#error_explanation').clone().show(), 'html')
        .show()
    });
    </script>
  <% end %>

  <div class='tabs'>
    <ul id='tab-menu' class='nav nav-tabs'>
      <li class='active'>
        <a href="#ad-setup" data-toggle='tab'>Criar anúncio</a>
      </li>  
    </ul>

    <div class='tab-content'>
      <div id='ad-setup' class="tab-pane fade active in">
        <% if is_admin? %>
         <div class="field">
          <%= f.label "expira em (meses)" %> 
          <%= f.date_field :expires_at, placeholder: '12' %>
        </div> 
        <% end %>

        <% unless params[:category_id] %>
          <div class="field">
            <%= f.label :categoria %> <br>
            <%= f.select :category_id, Category.all.collect {|c| c[:name] } %> 
          </div>
        <% else %>
        <%= f.hidden_field :category_id %>
        <% end %>

        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class='field'>
          <h3>Envie uma logo</h3>
          <div id='preview'></div>
          <%= cl_image_upload_tag(:'ad[logo_url]') %>
        </div>

        <div class='form-group'>
          <%= f.text_field :name, placeholder: 'Seu negócio', class: 'input-lg' %>
        </div>
        
        <div class='form-group'>
          <%= f.text_field :slogan, placeholder: 'Seu slogan', class: 'input-lg' %>
        </div>

        <div class="field">
          <%= f.label :"site" %> 
          <small>Se não tiver um, é só deixar em branco</small><br>
          <%= f.url_field :site_url, placeholder: 'http://exemplo.com', class: 'input-lg' %>
        </div>  

        <div class='address'>
        <% unless @ad.address %>
          <div class='bg-warning'>Por favor, defina os dados de contato</div>
          <% new_address = Address.create(ad_id: @ad.id) %>
        <% end %>
          <%= f.fields_for :address do |a| %>
            <%= a.hidden_field :id %>
            <%= a.text_field :street, class:'input-lg', placeholder: 'Rua/Av.' %><br>
            <%= a.text_field :zipcode, class:'input-lg', placeholder: 'CEP' %><br>
            <%= a.text_field :neighbourhood, class:'input-lg', placeholder: 'Bairro' %><br>
            <%= a.text_field :complement, class:'input-lg', placeholder: 'Complemento' %><br>

            <div class='row'>
              <%= a.text_field :phone_area_code, class:'input-lg', placeholder: '00', maxlength: 2 %>
              <%= a.number_field :phone_number, class:'input-lg', placeholder: '9999-9999', maxlength: 9 %>
            </div>

            <%= a.collection_select(:state_id, State.all, :id, :name, class: 'form-control') %>
            <div id='ad-city'></div>
            <script type="text/x-tmpl" id='city-select-tmpl'>
              <select id='ad_address_attributes_city_id' name='ad[address_attributes][city_id]' class='form-control'>
                {% $.each(o.cities, function( i, city ){ %}
                  <option value="{%= city.id %}">{%= city.name %}</option>
                {% }); %}
              </select>
            </script>
            <script type="text/javascript">
              var stateSelect = $('#ad_address_attributes_state_id');
              stateSelect.change(function(){
                var stateID = $(this).val(); 
                City.get_by_state(stateID, function( cities ){
                  var citiesSelect = tmpl('city-select-tmpl', {cities: cities});
                  $('#ad-city').html(citiesSelect);
                });
              });
            </script>
          <% end %>
        </div>  

        <div class='well'>
          <h1>Coloque na caixa abaixo as informações sobre sua loja/serviço</h1>
        </div>   

        <div class="field"> 
          <%= f.text_area :description, rows: 15, style: 'width: 100%'%>
        </div>

        <div class="actions">
          <%= f.submit :class => 'btn btn-lg btn-success', value: 'Salvar' %>
        </div>

        </div>
      </div>

    </div>
  </div>
<% end %>
</div>

<script type="text/javascript">
  $(function(){
    $('.cloudinary-fileupload')
      .bind('fileuploadprogress', function(e, data){
        var percent = data.loaded/data.total; 
        NProgress.set( percent );
      })
      .bind('fileuploadsend', function(){ 
        NProgress.start(); 
        $('input[name=commit]').addClass('disabled').val('Espere a logo ser enviada...')
      })
      .bind('fileuploaddone', function(e, data){
        NProgress.done();
        $('input[name=commit]').removeClass('disabled').val('Criar anúncio');
        $('input[name*=logo_url]').val(data.result.public_id + '.' + data.result.format);

        $('#preview').html(
          $.cloudinary.image(data.result.public_id, 
              { format: data.result.format, version: data.result.version, 
                crop: 'fill', width: 150, height: 100 })
        );         
      })
      .bind('fileuploadfail', function(){
        NProgress.done();
        $('input[name=commit]').val('Erro ao enviar a logo')

        Modal
          .header('<h1>Falha ao fazer upload da logo!</h1>', 'html')
          .body('<p>Tente novamente.</p>', 'html')
          .footer('');
      });


      $('input[type!=submit], select').addClass('form-control');

      function loadLogoPreview( imageID, format ){
        $('#preview').html(
          $.cloudinary.image(imageID, { 
              format: format, 
              crop: 'fill', 
              width: 150, 
              height: 100 
          });        
      }
  })
</script>

app/views/ads/edit.html.erb
<h1>Editar anúncio</h1>

<% if !@ad.hidden? or admin_or_owner?(@ad) %>
    <%= render 'form' %>
<% else %>
    <h1><%= current_user.name %>, seu anúncio está congelado</h1>
    <p class='lead'>Se isso está acontecendo é porque seu pagamento expirou.<br>
    Mas não esquente, você pode pagar mais aqui <%= 'link' %>
    </p>
<% end %>

<%= link_to 'Ver este anúncio', category_ad_path(@ad.category, @ad) %> |
<%= link_to 'Ver todos os anúncios', ads_path(@category) %>

app/views/ads/index.html.erb
<%= render 'categories/show.html.erb' %>

app/views/ads/new.html.erb
<h1>Novo anúncio</h1>
<p class='lead muted'>Criando anúncio na categoria <%= content_tag :span, @category.name %></p>

<% if user_signed_in? %>
    <%= render 'form' %>
<% else %>
    <h1>Você não pode anunciar.</h1>
<% end %>

app/views/ads/show.html.erb
<h2><%= @ad.name %></h2>
<% unless @ad.hidden? %>
    <%= render 'ads/show/show' %>  
<% else %>
    <p class='lead'>Ops! <%= current_user.name %>, você precisa renovar ou criar um novo pagamento para que este anúncio possa ser visto.</p>
    <p><%= link_to 'Clique aqui para realizar um novo pagmento', new_category_ad_payment_path(@ad.category, @ad) %></p>
<% end %>