config/routes.rb
Catala::Application.routes.draw do
  devise_for :users, controller: 'registrations'
  
  get 'products/search'
  get 'pag_notifications/create'
  get 'payments/new' => 'payments#new'
  get 'city/get_by_state/:state_id', to: 'city#get_by_state'
  get 'image_uploader' => 'image_uploader#upload' 

 
  resources :categories do 
    resources :ads do
      
      resources :products do
        member do 
          get 'search'
        end
      end

      resources :payments
    end
  end

  root 'welcome#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :ads
    
    validates :name, :presence => true, :length => { :minimum => 5 }

    extend FriendlyId
    friendly_id :name, use: :slugged

    private
	    def should_generate_new_friendly_id?
	    	new_record?
	    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :is_admin?, only: [:update, :edit, :new, :create]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoria criada com sucesso.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoria atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find_by slug: params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
    
    def is_admin?
        redirect_to '/', notice: 'Você não é um admin' unless current_user.try(:admin?)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>Opa! <%= pluralize(@category.errors.count, "error") %> foram comitidos no formulário</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Salvar', :class => 'btn btn-success'  %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class='row-fluid categories-list'>
    <h1>Todas as categorias no Catala</h1>
    
    <style type='text/css'>
        .list-cats {
            font-size: 1.5em;
            font-family: 'Raleway', sans-serif;
            list-style: none;
        }
        
        .list-cats li {
            padding: 1.5em 0;
            border-top: 1px #ccc solid;
            border-bottom: 1px #ccc solid;
        }
        
        .list-cats i {
            padding: 20px;
            background-color: #ccc;
            color: #fff;
            transition: background-color 0.2s;
            -webkit-transition: background-color 0.2s;
            -moz-transition: background-color 0.2;
        }
        
        .list-cats i:hover { background-color: #4bf }
    </style>
    <ul class='style-none list-cats'>
        <% @categories.each_with_index do |cat,i| %>
        <li>
            <i><%= cat.ads.where(hidden: false).size %></i>
            <%= link_to cat[:name], cat %>
            <% if user_signed_in? %>
                | <%= link_to 'Criar anuncio nesta categoria', new_category_ad_path(cat.slug), class: 'btn btn-success' %>
            <% end %>
        </li>
        <% end %>
    </ul>
</div>

app/views/categories/new.html.erb
<br/>
<div class='text-center'>
    <h1>Nova categoria</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'Voltar', categories_path %>
</div>

app/views/categories/show.html.erb
    <h1><%= @category.name %></h1>
    
    <% ads = @category.ads.where('hidden = false') %>
    <p class='lead muted'>
        <%= pluralize(ads.size, 'anúncio') %> nesta categoria
    </p>

    <% if is_admin? %>
       <%= link_to 'Editar categoria', edit_category_path(@category), class: 'btn btn-danger' %>
    <% end %>
    <% if user_signed_in? %>
       <%= link_to 'Criar novo anúncio nesta categoria', new_category_ad_path(@category), class: 'btn btn-success' %>
    <% end %>
       
    <% if is_admin? and @category.ads.size > 0 %>
        <p class='lead muted'>
        <%= pluralize(@category.ads.where('hidden = true').size, 'anuncio frizado') %> nesta categoria também
        </p>
    <% end %>

    <div class='row'>
      <% ads.each do |ad, i| %>
            <%= render 'ads/ad_mini', ad: ad %>
      <% end %>
    </div>