config/routes.rb
Catala::Application.routes.draw do
  devise_for :users, controller: 'registrations'
  
  get 'products/search'
  get 'pag_notifications/create'
  get 'payments/new' => 'payments#new'
  get 'city/get_by_state/:state_id', to: 'city#get_by_state'
  get 'image_uploader' => 'image_uploader#upload' 

 
  resources :categories do 
    resources :ads do
      
      resources :products do
        member do 
          get 'search'
        end
      end

      resources :payments
    end
  end

  root 'welcome#index'
end

app/models/ad.rb
class Ad < ActiveRecord::Base
    belongs_to :category
    belongs_to :user

    has_many :payments
    has_many :products

    has_one :address
    accepts_nested_attributes_for :address, allow_destroy: true
    
    validates :name, presence: true, length: { minimum: 1 }
    validates :description, presence: true, length: { minimum: 10 }

    PRICE_PER_MONTH = 30

    extend FriendlyId
    friendly_id :name, use: :slugged

    private
	    def should_generate_new_friendly_id?
	    	new_record?
	    end    
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :city
  belongs_to :state
  belongs_to :user
  belongs_to :ad
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :ads
    
    validates :name, :presence => true, :length => { :minimum => 5 }

    extend FriendlyId
    friendly_id :name, use: :slugged

    private
	    def should_generate_new_friendly_id?
	    	new_record?
	    end
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state
  has_many :adresses
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :ad
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  belongs_to :ad
  
  validates :paid_months, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :ad
end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :cities
	has_many :addresses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :ads
  has_many :payments
  
  has_one :address
  accepts_nested_attributes_for :address,  allow_destroy: true
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  before_filter :is_user?, only: [:update, :edit, :destroy, :new]

  include AdsHelper
  include ProductsHelper
  
  # GET /ads
  # GET /ads.json
  def index
    @ads ||= Ad.all.where(hidden: false)
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @category = Category.friendly.find( params[:category_id] )
    @ad = @category.ads.build
  end

  # GET /ads/1/edit
  def edit
      @category = Category.friendly.find( params[:category_id] )
  end

  # POST /ads
  # POST /ads.json
  def create
    @category = Category.friendly.find( params[:category_id] )
    # TODO: clear :expires_at field here
    @ad = @category.ads.build( ad_params )
    
    if current_user.admin? 
      @ad.hidden = false
    end

    if request.xhr?
      if @ad.save
        render text: @ad.slug
      else
        render text: 'error'
      end
    else
      respond_to do |format|
        if @ad.save
          format.html { redirect_to ad_url( @ad ), notice: 'Seu anúncio foi criado com sucesso' }
          format.json { render action: 'show', status: :created, location: @ad }
        else
          format.html { render action: 'new' }
          format.json { render json: @ad.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Anúncio atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to '/' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find_by slug: params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list throug
    def ad_params
        address = [:id, :street, :zipcode, :neighbourhood, :complement, :phone_area_code, :phone_number, :state_id, :city_id]
        params.require(:ad).permit(
          :expires_at, :name, :slogan, :logo_url,:site_url,
          :state, :city, :district, :cep, :tel, :description, 
          :category_id, :user_id, :products, address_attributes: address
        )
    end
    
    def is_user?
        redirect_to '/', notice: 'Você não está logado' unless authenticate_user!
    end
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def get_by_state
  	state_id = params[:state_id]
  	cities = City.all.where(state_id: state_id)

  	render json: cities
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :new_address]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/ads_helper.rb
module AdsHelper
    def ad_url(ad)
        "/categories/#{ad.category.slug}/ads/#{ad.slug}"
    end
    
    def ads_path(cat)
        "/categories/#{cat.slug}/ads/"    
    end
    
    def edit_path(ad)
        "/categories/#{ad.category.slug}/ads/#{ad.slug}/edit"
    end
    
    def is_admin_or_owner?(ad)
        if user_signed_in?
           current_user.admin? or ad.user.id == current_user.id
        end
    end

    def is_admin_or_waiting_user?
        if user_signed_in?
            current_user.admin? or current_user.paid_but_not_yet_posted?
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def put_if_signed( msg )
        if user_signed_in?
            msg
        end
    end
    
    def put_if_admin( msg )
        if current_user.try(:admin?)
            msg
        end
    end
    
    def is_admin?
        current_user.try(:admin?)
    end

    def admin_or_owner?( ad )
        current_user.admin? || ad.user_id == current_user.id 
    end

    def bAlert(msg, type)
        "<div class='alert alert-#{type}'>#{msg}</div>"
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
    def price_per_month
        30
    end
    
    def redirect_url
        'http://catala.com.br'
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def new_product_url(ad)
		"/categories/#{ad.category.slug}/ads/#{ad.slug}/product/new"
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catala</title>
  <meta charset='utf-8'/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="index,follow">
  <meta name="keywords" content="lojas, onde comprar, catalogo, agua branca, piaui" /> 
  <meta property="fb:admins" content="grubens1"/>
  <meta property="og:type" content="site"/>
  <meta property='og:title' content='Catala | Mais que um catálogo'/>
  <!--<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>-->
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    Category.categories = <%= raw Category.all.to_json %>;
  </script>
  <link rel='shortcut icon' href='<%= asset_path('favicon.png') %>'>
</head>
<body>

<div class="modal fade" id="main-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" class='modal-close-btn'>Fechar</button>
        <button type="button" class="btn btn-primary" class='modal-save-btn'>Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
    <div class='container'>
    <div id='menu'>
      <ul class='nav nav-pills'>

        <li><%= link_to 'Catala', '/' %></li>
        <% cats ||= Category.all.first(7) %>
        <% cats.each do |cat| %>
          <li><%= link_to cat[:name], cat %></li>
        <% end %>
          <li class='active'><%= link_to 'Mostrar tudo', '/categories' %></li>
        <% unless user_signed_in? %>
          <li class='active'>
            <%= link_to 'Entrar', new_session_path(:user) %>
          </li>
        <% else %>
          <li class='active'>
            <%= link_to 'Sair', destroy_session_path(:user), method: :delete %>
          </li>
          <li class='active'>
            <%= link_to 'Minha conta', edit_user_registration_path %>
          </li>
        <% end %>
        <% if is_admin? %>
          <li><%= link_to 'Criar nova', new_category_path %></li>
        <% end %>        
      </ul>
    </div>
  </div>

  <div class='container'>
    <%= raw bAlert(notice, 'info') if notice %>
    <%= raw bAlert(alert, 'danger') if alert %>
    
    <%= yield %>

  </div>
  
    <script type='text/javascript'>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    
      ga('create', 'UA-44008860-1', 'catala.com.br');
      ga('send', 'pageview');
    
    </script>    
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=358540094266384";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>    
</body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  null, // 'form', or 'json' (default json)
        saveMethod: null, // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>